package Frames;


import Loader.Question;
import Loader.QuestionLoader;
import Database.MillionaireConnection;
import java.util.List;
import javax.swing.JButton;

public class GameFrame extends javax.swing.JFrame {

    private final int QUESTION_SIZE = 10;
    private final List<Question> questions;

    private int stage = 0;
    private boolean victory = false;

    public GameFrame(MillionaireConnection connection, String type) {
        initComponents();
        
        questions = new QuestionLoader(connection).getRandom(type, QUESTION_SIZE + 1);

        setQuestion(questions.get(stage));
    }

    private void setQuestion(Question question) {
        javax.swing.JButton[] buttons = new javax.swing.JButton[]{
            button_answer1,
            button_answer2,
            button_answer3,
            button_answer4,
            button_answer5,
            button_answer6
        };

        button_next.setEnabled(false);
        button_quit.setEnabled(false);

        area_question.setText(question.text);
        for (JButton button : buttons) {
            button.setText("");
            button.setEnabled(false);
        }
        for (int i = 0; i < question.size; i++) {
            buttons[i].setEnabled(true);
            buttons[i].setText(question.answers.get(i));
        }
    }

    private void answerAndCheck(int pos) {
        javax.swing.JButton[] buttons = new javax.swing.JButton[]{
            button_answer1,
            button_answer2,
            button_answer3,
            button_answer4,
            button_answer5,
            button_answer6
        };
        for (JButton button : buttons) {
            button.setEnabled(false);
        }

        if (pos == questions.get(stage).rightAnswerPos) {
            button_next.setEnabled(true);
        } else {
            button_quit.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_answer1 = new javax.swing.JButton();
        button_answer2 = new javax.swing.JButton();
        button_answer3 = new javax.swing.JButton();
        button_answer4 = new javax.swing.JButton();
        button_answer5 = new javax.swing.JButton();
        button_answer6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_question = new javax.swing.JTextArea();
        button_next = new javax.swing.JButton();
        button_quit = new javax.swing.JButton();
        label_reward = new javax.swing.JLabel();
        label_got = new javax.swing.JLabel();
        label_stage = new javax.swing.JLabel();
        timerBar = new javax.swing.JProgressBar();
        button_addTime = new javax.swing.JButton();
        button_remove = new javax.swing.JButton();
        button_change = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        button_answer1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_answer1.setText("a1");
        button_answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_answer1ActionPerformed(evt);
            }
        });

        button_answer2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_answer2.setText("a2");
        button_answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_answer2ActionPerformed(evt);
            }
        });

        button_answer3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_answer3.setText("a3");
        button_answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_answer3ActionPerformed(evt);
            }
        });

        button_answer4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_answer4.setText("a4");
        button_answer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_answer4ActionPerformed(evt);
            }
        });

        button_answer5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_answer5.setText("a5");
        button_answer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_answer5ActionPerformed(evt);
            }
        });

        button_answer6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_answer6.setText("a6");
        button_answer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_answer6ActionPerformed(evt);
            }
        });

        area_question.setEditable(false);
        area_question.setColumns(20);
        area_question.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        area_question.setLineWrap(true);
        area_question.setRows(5);
        area_question.setWrapStyleWord(true);
        area_question.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        area_question.setFocusable(false);
        area_question.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(area_question);

        button_next.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_next.setText("Next");
        button_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nextActionPerformed(evt);
            }
        });

        button_quit.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_quit.setText("Quit");
        button_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_quitActionPerformed(evt);
            }
        });

        label_reward.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_reward.setText("Next");

        label_got.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_got.setText("Got");

        label_stage.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_stage.setText("Stage");

        button_addTime.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_addTime.setText("Add 30s");
        button_addTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addTimeActionPerformed(evt);
            }
        });

        button_remove.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_remove.setText("Remove a wrong answer");
        button_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_removeActionPerformed(evt);
            }
        });

        button_change.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_change.setText("Change a question");
        button_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_addTime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_change, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(timerBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_answer5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(button_answer6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(button_answer4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_answer2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_got, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_reward, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(label_stage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_got)
                    .addComponent(label_reward)
                    .addComponent(label_stage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timerBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(button_addTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(button_remove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_change, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_answer3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(button_answer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_answer6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_answer5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_quit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_answer1ActionPerformed
        answerAndCheck(1);
    }//GEN-LAST:event_button_answer1ActionPerformed

    private void button_answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_answer2ActionPerformed
        answerAndCheck(2);
    }//GEN-LAST:event_button_answer2ActionPerformed

    private void button_answer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_answer3ActionPerformed
        answerAndCheck(3);
    }//GEN-LAST:event_button_answer3ActionPerformed

    private void button_answer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_answer4ActionPerformed
        answerAndCheck(4);
    }//GEN-LAST:event_button_answer4ActionPerformed

    private void button_answer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_answer5ActionPerformed
        answerAndCheck(5);
    }//GEN-LAST:event_button_answer5ActionPerformed

    private void button_answer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_answer6ActionPerformed
        answerAndCheck(6);
    }//GEN-LAST:event_button_answer6ActionPerformed

    private void button_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nextActionPerformed
        if (stage == 10)
        
        setQuestion(questions.get(stage++));
    }//GEN-LAST:event_button_nextActionPerformed

    private void button_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_quitActionPerformed

        setQuestion(questions.get(stage++));
    }//GEN-LAST:event_button_quitActionPerformed

    private void button_addTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_addTimeActionPerformed

    private void button_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_removeActionPerformed

    private void button_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_changeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_changeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_question;
    private javax.swing.JButton button_addTime;
    private javax.swing.JButton button_answer1;
    private javax.swing.JButton button_answer2;
    private javax.swing.JButton button_answer3;
    private javax.swing.JButton button_answer4;
    private javax.swing.JButton button_answer5;
    private javax.swing.JButton button_answer6;
    private javax.swing.JButton button_change;
    private javax.swing.JButton button_next;
    private javax.swing.JButton button_quit;
    private javax.swing.JButton button_remove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_got;
    private javax.swing.JLabel label_reward;
    private javax.swing.JLabel label_stage;
    private javax.swing.JProgressBar timerBar;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        new GameFrame(new MillionaireConnection(), "Test").setVisible(true);
    }
}
