package Frames;

import Database.GameRecord;
import Database.MillionaireConnection;
import java.util.List;

public class HistoryFrame extends javax.swing.JFrame {

    private final MillionaireConnection connection;
    private final String username;

    /**
     * Creates new form HistoryFrame
     *
     * @param connection Connection of DB
     * @param username name of user
     */
    public HistoryFrame(MillionaireConnection connection, String username) {
        this.connection = connection;
        this.username = username;

        initComponents();
    }

    public void setVisialeAndRefresh() {
        setVisible(true);
        List<GameRecord> list = this.connection.getRecords(username);
        Object[][] objects = new Object[list.size()][4];
        for (int i = 0; i < list.size(); i++) {
            objects[i][0] = list.get(i).getDate();
            objects[i][1] = list.get(i).getFailure();
            objects[i][2] = list.get(i).getStage();
            objects[i][3] = list.get(i).getMoney();
        }

        table_history.setModel(new javax.swing.table.DefaultTableModel(
                objects,
                new String[]{
                    "Date", "Failure", "Stage", "Money"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_history = new javax.swing.JTable();

        setTitle("History");

        table_history.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        table_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Failure", "Stage", "Money"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_history);
        if (table_history.getColumnModel().getColumnCount() > 0) {
            table_history.getColumnModel().getColumn(0).setResizable(false);
            table_history.getColumnModel().getColumn(1).setResizable(false);
            table_history.getColumnModel().getColumn(2).setResizable(false);
            table_history.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_history;
    // End of variables declaration//GEN-END:variables
}
