package Frames;

import Database.MillionaireConnection;

/**
 * The layout of this frmae is mostly gemerated by NetBeans
 */
public class MainFrame extends javax.swing.JFrame {

    private final MillionaireConnection connection;
    private final String username;

    private final String questionType1 = "Normal";
    private final String questionType2 = "Hard";
    private final String questionType3 = "Extreme";

    private final HistoryFrame historyFrame;

    /**
     * Creates new form MainFrame
     *
     * @param connection Connection of DB
     * @param username Username of user
     */
    public MainFrame(MillionaireConnection connection, String username) {
        this.connection = connection;
        this.username = username;
        historyFrame = new HistoryFrame(connection, username);

        initComponents();
        java.awt.Point p = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        setLocation(p.x - getWidth() / 2, p.y - getHeight() / 2);

        button_start1.setText(questionType1);
        button_start2.setText(questionType2);
        button_start3.setText(questionType3);
        
        refreshData();
    }

    public final void refreshData() {
        display_username.setText(username);
        display_money.setText(String.valueOf(connection.getMoneyByName(username) + "k"));
    }

    public String getUsername() {
        return username;
    }

    private void startGame(String type) {
        setVisible(false);
        historyFrame.setVisible(false);
        java.awt.EventQueue.invokeLater(() -> {
            new GameFrame(connection, type, this).setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_start2 = new javax.swing.JButton();
        button_quit = new javax.swing.JButton();
        display_money = new javax.swing.JLabel();
        display_username = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_money = new javax.swing.JLabel();
        button_history = new javax.swing.JButton();
        button_start1 = new javax.swing.JButton();
        button_start3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Who want to be a MILLIONAIRE");
        setResizable(false);

        button_start2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_start2.setText("Start a new game");
        button_start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAction2(evt);
            }
        });

        button_quit.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_quit.setText("Quit");
        button_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitAction(evt);
            }
        });

        display_money.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        display_money.setText("Money");

        display_username.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        display_username.setText("Username");

        label_name.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_name.setText("Name: ");

        label_money.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_money.setText("Money: ");

        button_history.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_history.setText("History");
        button_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyAction(evt);
            }
        });

        button_start1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_start1.setText("Start a new game");
        button_start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAction1(evt);
            }
        });

        button_start3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_start3.setText("Start a new game");
        button_start3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAction3(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_start1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_start2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(button_start3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_money, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(display_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(display_money, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(button_history, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(button_quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(display_username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_money, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(display_money, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(button_start1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_start2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_history, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_start3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(button_quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        button_start2.getAccessibleContext().setAccessibleName("button_start");
        button_quit.getAccessibleContext().setAccessibleName("button_quit");
        display_money.getAccessibleContext().setAccessibleName("label_money");
        display_username.getAccessibleContext().setAccessibleName("label_username");
        label_name.getAccessibleContext().setAccessibleName("labelText_username");
        label_money.getAccessibleContext().setAccessibleName("labelText_money");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historyAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyAction
        historyFrame.setVisialeAndRefresh();
    }//GEN-LAST:event_historyAction

    private void quitAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitAction
        System.exit(0);
    }//GEN-LAST:event_quitAction

    private void startAction1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAction1
        startGame(questionType1);
    }//GEN-LAST:event_startAction1

    private void startAction2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAction2
        startGame(questionType2);
    }//GEN-LAST:event_startAction2

    private void startAction3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAction3
        startGame(questionType3);
    }//GEN-LAST:event_startAction3

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_history;
    private javax.swing.JButton button_quit;
    private javax.swing.JButton button_start1;
    private javax.swing.JButton button_start2;
    private javax.swing.JButton button_start3;
    private javax.swing.JLabel display_money;
    private javax.swing.JLabel display_username;
    private javax.swing.JLabel label_money;
    private javax.swing.JLabel label_name;
    // End of variables declaration//GEN-END:variables
}
